version: '3'
services:
  notification-service:
    image: notification-service
    container_name: notification-service
    ports:
      - 5556:5556
    networks:
      - training

  expense-service:
    image: expense-service
    container_name: expense-service
    ports:
      - 5555:5555
    networks:
      - training

  user-service:
    image: user-service
    container_name: user-service
    ports:
      - 5557:5557
    networks:
      - training

  ui:
    depends_on:
      - expense-service
      - user-service
    image: ui
    container_name: ui
    ports:
      - 80:80
    networks:
      - training

networks:
  training:
    driver: bridge